name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Root Dependencies
      run: npm ci

    - name: Install Web Dependencies
      run: npm ci
      working-directory: ./web

    - name: Build Backend Pipeline
      run: npm run build

    - name: Build Web Pipeline
      run: npm run build
      working-directory: ./web
